version: 2.1
jobs:
  hello_job:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Run Hello script
          command: |
            bash src/test_hello.sh
  goodbye_job:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Run Goodbye script
          command: |
            bash src/test_goodbye.sh

workflows:
  version: 2
  hello:
    when: << pipeline.parameters.run_workflow_hello >>
    jobs:
      - hello_job
  goodbye:
    when: << pipeline.parameters.run_workflow_goodbye >>
    jobs:
      - goodbye_job

parameters:
  run_workflow_hello:
    default: true
    type: boolean

  run_workflow_goodbye:
    default: true
    type: boolean